name: Trigger Automation Tests

on:
  push:
    branches:
      - main

jobs:
  trigger-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger automation repo workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.AUTOMATION_REPO_TOKEN }}" \
          https://api.github.com/repos/chikasbitlet/githubactionsplayw/actions/workflows/playwright.yml/dispatches \
          -d '{"ref":"main","inputs":{"environment":"stg"}}'
